version: '3.8'

services:


  api: #rubyね
    build:
      context: ./api/
      dockerfile: Dockerfile.prod
    #volumes:
    #  - socket:/app/tmp
    #  - public:/app/public
    ports:               #変更(追加)
      - 3000:3000
    #本番環境ではオフ！
    depends_on:
      - db

  #app:
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile.prod
  #  ports:
  #    - 80:80
  #  depends_on:
  #    - db


  db:
    image: mysql:5.7
    ports:
      - "4306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./api/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password


  web:
    build:
      context: ./front/
      dockerfile: Dockerfile.prod
    #volumes:
    #  - socket:/app/tmp
    #  - public:/app/public
    ports:
      - 80:80
    depends_on:
      - api
      #- front

volumes:
  public:
  socket:
